export const refObject = [
  {
    src: "/img/reference/khs.png",
    thumbnail: "/img/reference/khs.png",
    alt: "Horský oddíl Zlín",
    media_type: "image",
    url: "https://www.khszlin.com",
    description: "Webový portál horolezeckého oddílu Zlín",
    website: "khszlin.com",
    dialogTitle: "Next.js + PostgreSQL + Tailwind + Google Cloud",
    dialogContext:
      "Komunitní platforma pro horolezecký oddíl s vlastním CMS systémem. Klíčové funkce zahrnují: integrovaný content management systém přímo ve webu, automatickou serverovou optimalizaci a komprimaci fotografií, real-time úpravy článků, komplexní uživatelské profily s vlastními avatary, systém lajkování a komentářů, responzivní design optimalizovaný pro všechny typy zařízení. Celá aplikace je postavena na moderním tech stacku s automatizovaným CI/CD deploymentem a škálovatelnou cloud infrastrukturou - vše co potřebuje aktivní horolezecká komunita pro sdílení zážitků, plánování a rozvoj.",
  },
  {
    src: "/img/reference/odsrdecka-reference.png",
    thumbnail: "/img/reference/odsrdecka-reference.webp",
    alt: "Od srdéčka",
    media_type: "image",
    url: "https://odsrdecka.cz/",
    description: "Dorty a sladké bary z Kašavy",
    website: "odsrdecka.cz",
    dialogTitle: "Next.js + Wordpress jako headless CMS + Tailwind",
    dialogContext: "",
  },
  {
    src: "/img/reference/holesov.png",
    thumbnail: "/img/reference/holesov.webp",
    alt: "Haly Holešov",
    media_type: "image",
    url: "https://halyholesov.cz/",
    description: "Pronájem průmyslových hal v Holešově",
    website: "halyholesov.cz",
    dialogTitle: "Next.js + Wordpress jako headless CMS + Tailwind",
    dialogContext: "Web je spuštěn zatím bez nabídek nemovitostí",
  },
];
